name: Integration Test
on:
  pull_request_review:
    types: [submitted]

env:
  INTEGRATION_TEST_AUTH_JSON: ${{ secrets.INTEGRATION_TEST_AUTH_JSON }}

jobs:
  integration_test:
    runs-on: ubuntu-latest
    environment: integration_test
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Python 3.10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: "pip"
      - run: ./scripts/dev.sh
      - run: ./scripts/integration_test.sh
    if: github.event.review.state == 'approved'
