name: Integration Test
on: 
  workflow_dispatch:

env:
  T_SERVICE_ACCOUNT_INFO: ${{ secrets.T_SERVICE_ACCOUNT_INFO }}

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Python ${{ matrix.python-version }} 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
      - run: ./scripts/dev.sh
      - run: ./scripts/integration_test.sh
