name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Flit
        run: pip install flit

      - name: Install Dependencies
        run: flit install --symlink

      - name: Publish PyPI
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
        run: bash scripts/publish_pypi.sh

      - name: Install pdoc
        run: pip install pdoc3

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish Docs
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: bash scripts/publish_docs.sh
